export const SET_USER_DATA_SUCCEED = 'SET_USER_DATA_SUCCEED';
export const SET_USER_DATA_FAILED = 'SET_USER_DATA_FAILED';
export const SET_USER_DATA_RESET = 'SET_USER_DATA_RESET';

export const GET_AUTHENTICATION_SUCCEED = 'GET_AUTHENTICATION_SUCCEED';
export const GET_AUTHENTICATION_FAILED = 'GET_AUTHENTICATION_FAILED';
export const GET_AUTHENTICATION_RESET = 'GET_AUTHENTICATION_RESET';

export const GET_LOGIN_STATUS_SUCCEED = 'GET_LOGIN_STATUS_SUCCEED';
export const GET_LOGIN_STATUS_FAILED = 'GET_LOGIN_STATUS_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';