export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_ONE_ITEM_TO_CART = 'ADD_ONE_ITEM_TO_CART';
export const DROP_ONE_ITEM_FROM_CART = 'DROP_ONE_ITEM_FROM_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const RESET_CART = 'RESET_CART';