export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCEED = 'GET_CATEGORIES_SUCCEED';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

export const GET_SUBCATEGORIES = 'GET_SUBCATEGORIES';
export const GET_SUBCATEGORIES_SUCCEED = 'GET_SUBCATEGORIES_SUCCEED';
export const GET_SUBCATEGORIES_FAILED = 'GET_SUBCATEGORIES_FAILED';