export const ADD_TO_ORDERS = 'ADD_TO_ORDERS';
export const ADD_TO_ORDERS_SUCCEED = 'ADD_TO_ORDERS_SUCCEED';
export const ADD_TO_ORDERS_FAILED = 'ADD_TO_ORDERS_FAILED';

export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_SUCCEED = 'GET_ORDERS_SUCCEED';
export const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED';