export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCEED = 'GET_PRODUCTS_SUCCEED';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const FILTER_PRODUCTS_ON_CATEGORY = 'FILTER_PRODUCTS_ON_CATEGORY';
export const FILTER_PRODUCTS_ON_SUBCATEGORY = 'FILTER_PRODUCTS_ON_SUBCATEGORY';