export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const GET_PRODUCT_DETAILS_SUCCEED = 'GET_PRODUCT_DETAILS_SUCCEED';
export const GET_PRODUCT_DETAILS_FAILED = 'GET_PRODUCT_DETAILS_FAILED';
export const RESET_PRODUCT_DETAILS = 'RESET_PRODUCT_DETAILS';